id: PAB733018
initial_creation_type: input
source_metadata:
  title: Khenchen Ngawang Lodrö Rinchen
  language: es
  description: 'Texts by Khenchen Ngawang Lodrö Rinchen (mkhan chen ngag dbang blo
    gros rin chen, 1892–1952):'
  volume:
    18405251f3a5425e91466239dccdfb11:
      title: Prayer for the Long Life of Kyabgön Sakya Trichen
      parent: Long Life Prayers
created_at: '2022-03-01T00:21:03.087711'
last_modified_at: '2022-03-01T00:21:03.087715'
